project:
  type: book
  output-dir: docs
  
execute: 
  warning: FALSE
  message: FALSE
  cache: true
  freeze: auto

comments:
  hypothesis: 
    theme: clean

book:
  title: "Growthscapes"
  author: "Jeff Baldock et al."
  date: today
  chapters:
    - index.qmd
    - part: "Define Core Functions"
      chapters:
        - Habitat.qmd
        - Functions.qmd
        - SimulationLoop.qmd
        - PlotResults.qmd
    - part: "Pre-Calculate Growth and Growth Regime"
      chapters:
        - PreCalGrowth.qmd
        - GrowthRegime.qmd
    - part: "Define and Run Experiments"
      chapters:
        - ScenarioDefs.qmd
    - part: "Scenario Results"
      chapters:
        - Scenario_1_null_cold.qmd
        - Scenario_2_temp_mult.qmd
        - Scenario_3_temp_offset.qmd
        - Scenario_4_temp_offset_diffP.qmd


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
    number-depth: 4
        
    include-in-header:
      - file: github-corner.html
    code-link: true
      
  pdf:
    documentclass: scrreprt

editor: source