project:
  type: book
  output-dir: docs
  
execute: 
  warning: FALSE
  message: FALSE
  cache: true
  freeze: auto

comments:
  hypothesis: 
    theme: clean

book:
  title: "Growthscapes"
  author: "Jeff Baldock et al."
  date: today
  chapters:
    - index.qmd
    - part: "Define Core Functions"
      chapters:
        - Habitat.qmd
        - Functions.qmd
        - SimulationLoop.qmd
        - PlotResults.qmd
    - part: "Pre-Calculate Growth and Growth Regime"
      chapters:
        - PreCalGrowth.qmd
        - GrowthRegime.qmd
    - part: "Define Experiments and Sensitivity Analysis"
      chapters:
        - ScenarioDefs.qmd
        - SensitivityAnalysis.qmd
    - part: "Results"
      chapters:
        - ViewSimResults.qmd
        # - CompareFixedHab.qmd


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
    number-depth: 4
    toc: true
    toc-depth: 5
        
    include-in-header:
      - file: github-corner.html
    code-link: true
      
  pdf:
    documentclass: scrreprt

editor: source

permissions:
  contents: read
  pages: write
  id-token: write
