# Introduction

This book supports the NWCASC-funded project evaluating the value of migratory life histories to cold-water fish population dynamics. Our work is framed around the concept of "growthscapes", whereby migratory fish that couple complementary thermal habitat (i.e., growth potential) can attain larger body sizes compared to resident fish (Armstrong et al. 2021). This project seeks to understand the population-level outcomes of these individual migratory behaviors. This project is a collaboration between Oregon State University, Trout Unlimited, Montana State University, and University of Georgia.

Author: Jeff Baldock, <baldockj@oregonstate.edu>

Collaborators: Jonny Armstrong, Tim Cline, Helen Neville, Dan Dauwalter, Emma Lundberg, and Seth Wenger.

***  

<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" >Session Information</button><div id="collapseOne" class="accordion-collapse collapse"><div>

```{r}
sessionInfo()
```

</div></div>  

